### ISSUE TITLE
Can I confirm the license?

### ISSUE THREAD

**Issue by pragdave** [microsoft/uts2#1]
I know there's an MIT License file, but at the same time the `uts.ts` file has

~~~ js
/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
~~~

with no mention of the license.

Would it be possible to clarify this, perhaps by putting a License section into the README?

~~~ markdown
### License

This project is copyright © 2020 «name»
Copyright holder licenses it under the terms contained in [LICENSE.md](./LICENSE.md) (an MIT license).
~~~

Cheers

Dave

**Comment by connor4312** [comment]
The license can be found in the [`LICENSE` file](https://github.com/microsoft/uts2/blob/main/LICENSE) as well as license fields in the the package.json
